! $Id: generate_covar.F90 1604 2016-05-30 06:42:16Z lnerger $
!BOP
!
! !Program: generate_covar --- Compute covariance matrix from state trajectory
!
! !INTERFACE:
PROGRAM generate_covar

! !DESCRIPTION:
! This programm to computes a covariance matrix from a
! model trajectory of Lorenz96. The matrix is decomposed in
! EOFs and stored in form of eigenvalues and eigenvectors.
!
! The matrix is generated by a singular value decomposition
! of the perturbation matrix of a long state trajectory
! about its long time mean.

! !USES:
  IMPLICIT NONE

! Local variables
  INTEGER :: i, k, s, iter, maxtimes, rank      ! Counters
  CHARACTER(len=120) :: inpath, outpath         ! File paths
  CHARACTER(len=120) :: infile, outfile         ! File names
  CHARACTER(len=150) :: ncfile_in, ncfile_out   ! File name including path
  CHARACTER(len=150) :: attstr                  ! Attribute string for NC (NetCDF) output
  INTEGER :: ncid_in, ncid_out                  ! NC file IDs
  INTEGER :: id_dim, id_time, id_state          ! NC dimension and variable IDs
  INTEGER :: id_mean, id_sigma, id_svec         ! NC dimension and variable IDs
  INTEGER :: dimid_rank, dimid_state, dimid_one ! NC dimension and variable IDs
  INTEGER :: steps, dim_state                   ! Dimensions
  INTEGER :: stat(100)                          ! Status for NC operations
  INTEGER :: countv(2), startv(2)               ! Vectors for NC operations
  INTEGER :: dimids(2)                          ! Vector for NC operations
  REAL :: limit                                 ! Lower limit for singular values
  REAL, ALLOCATABLE :: times(:)                 ! Array of times from NC file
  REAL, ALLOCATABLE :: states(:, :)             ! State trajectory
  REAL, ALLOCATABLE :: meanstate(:)             ! Mean state of trajectory
  INTEGER :: status_covar                             ! Status Flag
  REAL,ALLOCATABLE,DIMENSION(:) :: svals        ! field of singular values
  REAL,ALLOCATABLE,DIMENSION(:,:) :: svdU       ! left singular vectors

  ! Controls for PDAF_eofcovar
  INTEGER :: remove_mean  ! (1) Let PDAF_eofcovar compute and subtract the mean state;
                          ! (0) mean already removed from trajectory
  INTEGER :: do_mv        ! (1) to perform multivariate normalization; (0) no normalization

  ! Unused, but required variables for PDAF_eofcovar
  INTEGER :: nfields        ! Number of fields
  INTEGER :: dim_fields(1)  ! Size of field (only for multivariate scaling (not used here))
  INTEGER :: offsets(1)     ! Offset of fields (only for multivariate scaling (not used here))
  INTEGER :: stddev(1)      ! STDDEV of field (only for multivariate scaling (not used here))

  !My variables
  CHARACTER(len=4) :: timestr
  CHARACTER(len=120) :: statefile


! ************************************************
! *** Configuration                            ***
! ************************************************

  ! Maximum number if time slices to consider
  maxtimes = 1000000

  ! Lower limit for eigenvalue
  limit = 1.0e-12


! ************************************************
! *** Init                                     ***
! ************************************************

  WRITE (*,'(10x,a)') '*******************************************'
  WRITE (*,'(10x,a)') '*             GENERATE_COVAR              *'
  WRITE (*,'(10x,a)') '*                                         *'
  WRITE (*,'(10x,a)') '*    Compute covariance matrix and mean   *'
  WRITE (*,'(10x,a)') '*     state from a sequence of states.    *'
  WRITE (*,'(10x,a)') '*                                         *'
  WRITE (*,'(10x,a)') '*   Write covar matrix as scaled eigen-   *'
  WRITE (*,'(10x,a)') '*    vectors and singular values into     *'
  WRITE (*,'(10x,a)') '*              NetCDF file                *'
  WRITE (*,'(10x,a/)') '*******************************************'


! ************************************************
! *** Open trajectory file and read dimensions ***
! ************************************************

  ! Get dimensions
  !State dimension
  dim_state = 10000
  steps = 400

  ! Initialize time array
  ALLOCATE(times(steps))

  WRITE (*,'(/1x,a)') 'Dimensions of experiment:'
  WRITE (*,'(5x,1x,a,i10)') 'state dimension', dim_state
  WRITE (*,'(11x,a,i10)')   'time steps', steps

  IF (steps < maxtimes) THEN
     WRITE (*,'(1x,a)') '!! Number of available time slices is smaller than maxtimes - resetting!'
     maxtimes = steps
  END IF
  WRITE (*,'(13x,a8,i10)') 'maxtimes', maxtimes


! ****************************
! *** Read trajectory data ***
! ****************************

  WRITE (*,'(/1x,a)') '------- Read trajectory -------------'

  ALLOCATE(states(dim_state, maxtimes))
  ALLOCATE(meanstate(dim_state))

  read_in: DO iter = 1, maxtimes
      write(timestr, '(i3.1)') iter
      statefile = trim(adjustl('../_output/state.q'//trim(adjustl(timestr))))
      open(22, file=statefile, status='old')
      read(22, *) states(1:dim_state, iter)
      close(22)

  END DO read_in

! *********************************************************
! *** Singular value decomposition of covariance matrix ***
! ***                                                   ***
! *** The covariance matrix is given by the state       ***
! *** sequences X of k states as                        ***
! ***          -1    _     _ T        T                 ***
! *** P = (k-1)   (X-X) (X-X)  = U L U  (EVP)           ***
! ***                                                   ***
! *** Thus we compute the singular value decomposition  ***
! ***     _        T            -1    2  T              ***
! ***   X-X = U S V ;  P = (k-1)   U S  U               ***
! ***                                                   ***
! ***                         -1/2                      ***
! *** and we store U and (k-1)     S in a NetCDF file.  ***
! *********************************************************

  WRITE (*,'(/1x,a)') '------- Compute covariance matrix decomposition -------------'

  ! PDAF_eofcovar should compute and subtract the mean state from Trajectory 
  ! before decomposition. Afterwards, it's added again.
  remove_mean = 1

  ! Set some variables only used for multivariate normalization - not here!
  nfields = 1      ! One field
  dim_fields = 10000  ! Size of field
  offsets = 0      ! offset of field from beginning of vector
  do_mv = 0   ! For testing one cat set do_mv=1 to activate normalization
  ! Note: multivariate normalization can be useful if there are several fields
  !       with difference variances. Here, we only have one field

  ! Allocate arrays for singular values and vectors
  ALLOCATE(svals(maxtimes))
  ALLOCATE(svdU(dim_state, maxtimes))

  ! Call routine generating matrix decomposition
  CALL PDAF_eofcovar(dim_state, maxtimes, nfields, dim_fields, offsets, &
       remove_mean, do_mv, states, stddev, svals, svdU, meanstate, status_covar)


! *********************************************************
! *** Write mean state and decomposed covariance matrix ***
! *********************************************************

! *** Determine rank to write ***

  getlimit: DO i = 1, maxtimes
     IF (svals(i) >= limit) THEN
        rank = i
     ELSE
        EXIT getlimit
     END IF
  END DO getlimit
  IF (rank < maxtimes) THEN
     WRITE (*,'(1x,a,i6,a,es10.2)') &
          'Use maximum of ', rank, ' eigenvectors due to eigenvalue-limit of ',limit
  END IF
  IF (rank == maxtimes) THEN
     rank = maxtimes - 1
     WRITE (*,'(5x,a,i4)') '++ reset rank to ',rank
  END IF

  WRITE (*,'(5x,a)') 'Singular values: '
  DO i = 1, rank
    WRITE (*, '(10x, i4, es12.3)') i, svals(i)
  END DO


  WRITE (*,'(/1x,a)') '------- Write decomposed covariance matrix and mean state -------------'

  ! Write singular values
  open(22, file='singular_values',status='replace')
  write(22,*) svals(:)
  close(22)


  ! Write mean state
  open(22, file='mean_state',status='replace')
  write(22,*) meanstate(:)
  close(22)

  ! *** Write singular vectors

  writevectors: DO i = 1, rank

    ! Write singular vector
    open(22, file='singular_vector',status='replace')
    write(22,*) svdU(:,i)
    close(22)

  END DO writevectors

! ********************
! *** Finishing up ***
! ********************

  DEALLOCATE(states, meanstate)
  DEALLOCATE(svals, svdU)

  WRITE (*,'(/1x,a/)') '------- END -------------'

END PROGRAM generate_covar

